baseURL = "/"
languageCode = "en-us"
title = "endomer"
Paginate = 1000
googleAnalytics = ""
theme = "showcase-hugo-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "endomer"
  description = "Página web principal del proyecto Encuestas Dominicanas en R (endomer)"
  message = "Es un proyecto que busca proveer herramientas útiles para trabajar con bases de datos de encuestas dominicanas en R."
  objetivo = "El objetivo principal es el de proveer la mayor cantidad de información posible relacionada con las encuestas. Así como funciones para calcular los principales indicadores que regularmente se calculan con dicha encuesta."
  hideAutoMenu = false

[social]
  twitter = "https://twitter.com/search?q=%23endomer&src=typed_query"
  github = "https://github.com/endomer"
